# Hyperparameters
NUM_GLYPHS = 32
LATENT_DIM = 32
NUM_TRANSFORMER_LAYERS = 4
D_MODEL = 256
NUM_HEADS = 8
DFF = 1024
RATE = 0.1
EPOCHS = 10
BATCH_SIZE = 16
RASTER_LOSS_WEIGHT = 1.0
VECTOR_LOSS_WEIGHT = 1.0
GEN_IMAGE_SIZE = (512, 512)
STYLE_IMAGE_SIZE = (168, 40)
MAX_COMMANDS = 150

ALPHABET = ["a", "d", "h", "e", "s", "i", "o", "n", "t"]
BASE_DIR = "/Users/simon/others-repos/fonts/ofl/"
